server:
  port: 8001
spring:
#  profiles:
#    active: native
  application:
    name: microservice-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/pipher-chen/config-repo
          label: master
#        native:
#          searchLocations: file:///D:/CodeSpace/pipher-springcloud-demo/config-repo

eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:8000/eureka/