server:
  port: 8000
  eviction-interval-timer-in-ms: 1000
eureka:
  server:
    enable-self-preservation: false
  instance:
    hostname: 127.0.0.1
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
